/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ims;

import com.ims.Item;
import com.google.gson.Gson;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Item item = new Item("Lenovo", "44879564", 447874, 69);
        
        Gson gson = new Gson();
        String item_json = gson.toJson(item);
        
        System.out.println(item_json);
    }
}
